### ISSUE TITLE
MissingRequirementError: object SimilarProductEngine not found

### ISSUE THREAD

**Issue by gongsy945** [rajdeepd/pio-engine-textclassfication-heroku#1]
Hi,rajdeepd
I tried to deploy pio-engine-textclassfication-heroku to Heroku , but it reported an exception:
Exception in thread "main" scala.reflect.internal.MissingRequirementError: 
object SimilarProductEngine not found.
at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
at scala.reflect.internal.Mirrors$RootsBase.ensureModuleSymbol(Mirrors.scala:126)
at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:161)
at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:21)
at io.prediction.workflow.WorkflowUtils$.getEngine(WorkflowUtils.scala:64)
at ServerApp$$anonfun$6.apply(ServerApp.scala:39)
at ServerApp$$anonfun$6.apply(ServerApp.scala:25)

**Comment by gongsy945** [comment]
<img width="1436" alt="9b069579-d7b2-42ab-a97e-9d8d4c94fb7e" src="https://cloud.githubusercontent.com/assets/4141978/21481370/d023564c-cba1-11e6-906a-013e3ebd5c0f.png">
